[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_core_staking = "FdQ9QdcVkYVqqGwCX8ghKiZAiDzYdbuC9c63rhuqVCmf"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
